# wt_ballistics_cal commit-hash: b83868e89a66f79c5fef36fcd1021c9b025eae6a 
# Repository: https://github.com/Warthunder-Open-Source-Foundation/wt_ballistics_calc
distance_flown = 12996.916687250732
distance_to_missile = 20400.0
max_v = 679.3885522028309
max_a = 80.0320775819693
min_a = -104.69070631651879
timestep = 0.1

[splash]
splash = false
at = 0.0

[parameters]
use_gravity = false
start_velocity = 340.0
distance_to_target = 0.0
target_speed = 0.0
altitude = 1000
